### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#168]
Post 1.0.0 we should figure out some ways to spread the word about regl.  This would involve giving some talks and maybe writing some articles.  Let's use this issue to start making a list of possible venues.

**Comment by Erkaman** [comment]
Another way of generating interest in the framework is writing cool demos. When I published that [wireframe world demo](https://github.com/Erkaman/wireframe-world), regl suddenly got a ton of [traffic](https://github.com/mikolalysenko/regl/graphs/traffic), and got like 30stars in two days.

Implementing something like realtime radiosity is also something that would result in a cool demo, and would probably generate even more interest in the framework. Especially since no one has ever done this in WebGL thus far. At least to my knowledge.

**Comment by rreusser** [comment]
It sounds trendy in a way that I don't necessarily like and might also be a bit early, but what about an `awesome-regl` repo with examples and tools? There are some interesting tools like [regl-recorder](https://github.com/Erkaman/regl-recorder) that would be nice to collect in a single place. The website would work, but the ease of a markdown PR might increase contributions.

**Comment by Erkaman** [comment]
Thank you. I added gl-fourier to the list in issue #181

**Comment by mikolalysenko** [comment]
Going to close this issue.  It is too vague.
