### ISSUE TITLE
Define "nodraw" commands that don't expect shaders

### ISSUE THREAD

**Issue by alvinsight** [regl-project/regl#394]
Hi guys, 
So far it feels like the thinking is that if we want a command that doesn't draw anything, then that command has to issue a callback that calls the other draw commands, like this:
```
setupCamera( () =>{
    drawBunny();
  })
```

Which is fine, although I'm not sure it's really documented, but my main point is that as your application grows in size you can see how this can get unwieldy really quickly, just with a few more features:
```
  setupCamera( () =>{

    setupScene( () =>{
      
      createSky( () => {
        drawBunny();
      })
    })
    
  })
```
yes, that would be a fancy bunny.

I'm aware this could be by design though, because even if this is cumbersome, I agree that it does centralise everything that happens during one frame in one place.
If this is the case, I guess maybe the docs should be a bit clearer on that point.

Otherwise it would be good to be able to define these "no draw" commands with a flag or something rather than nesting them.

**Comment by rreusser** [comment]
@alvinsight I may be misinterpreting, but I think the nesting might be necessary. If you type:

```javascript
commandThatSetsFramebufferA(() => {
  commandThatSetsFramebufferB(() => {
    draw1();
  })
  draw2();
})
```

Then you'd expect that `draw1` would write to `framebufferB` while `draw2` would write to `framebufferA`. So if a command sets a property, isn't the nesting required to ensure it properly unsets it? Does the nesting cause logical/data flow problems or is it more a matter of keeping the code structure nice? If the latter, then it might be more a matter of code organization and separating out functions to reduce the indentation if not the actual nesting.

Let me know if I'm misinterpreting though!

**Comment by alvinsight** [comment]
@rreusser You're right, sorry I just realised my comment might have been misleading, I just updated it.
What I think would be to be able to call a command that doesn't draw anything on its own like: 
```
setUpCameraAndTimeUniforms();
commandThatSetsFramebufferA(() => {
  commandThatSetsFramebufferB(() => {
    draw1();
  })
  draw2();
});
```
Just to reduce the amount of nesting, as at the moment the above would break.

**Comment by rreusser** [comment]
regl commands conceptually do three things when called:

1. set the state specified
2. either draw *or* call the provided function
3. restore the state

So if you didn't draw anything and you didn't nest a function, the command would simply set and then restore the state, which would be a waste. For the command do have any effect you'd need to remove step 3, but 'sticky' states like that would conflict with regl's effort to make things stateless. Otherwise you'd maybe want a command that sets state that's undone by the *parent* command, but currently the only way to do that is to make the data *part* of the parent command.

To be honest, the nesting bothered me too for a bit, but I found that with maybe one level of indirection by breaking up into functions, it hasn't really been a problem. (at least much less of a problem than dealing with state!)

**Comment by gregtatum** [comment]
I believe this issue goes against the design principles of regl. Thanks for the comments @alvinsight but I'm going to go ahead and close this as not actionable.

**Comment by alvinsight** [comment]
Hey @gregtatum no problem! I've found my way around setting context variables and other stuff that were not really brought forward in the examples, so I think this was mostly due to my lack of understanding of what `regl` really is for :)

**Comment by gregtatum** [comment]
Great, glad you worked it out!
