### ISSUE TITLE
Framebuffer not updating

### ISSUE THREAD

**Issue by mwmwmw** [regl-project/regl#444]
Hello, I'm relatively new to regl and I love it. 

I have a framebuffer setup to do some post-processing. The framebuffer is rendered for the first frame and is never updated again unless I resize the canvas. 

My renderer is an SDF raytracer. I suspect regl is not updating the framebuffer because the camera and object (plane) are not moving. 

Is there a way to force the framebuffer to update?

Here is my dead simple render loop. It only renders once and on resize. 

```
regl.frame(({ viewportWidth, viewportHeight }) => {

  fbo.resize(viewportWidth, viewportHeight);

  camera(()=>{
    raytrace();
    regl.clear({
      color: [0, 0, 0, 1],
      depth: 1,
      stencil: 0
    });
  });

  drawFBO();

})
```

**Comment by mwmwmw** [comment]
Sigh, I see the last time anyone responded here. Hopefully, you're all on vacation or something and this hasn't just been abandoned. 

No luck with the framebuffer.

I was able to get render to texture working, and so I just pass that into my post process shader now. Seems to work fine, but I'm not sure if this is the right thing to do.

```
regl.frame(({ viewportWidth, viewportHeight }) => {

  fbo.resize(viewportWidth, viewportHeight);

  camera(()=>{
    raytrace({feedback: feedback});
  });

  post({
    copy: true
  });

  postporcess({fbo: post});

  feedback({
    copy: true
  });

});
```

**Comment by gregtatum** [comment]
I'm not sure what exactly is going on with your issue, @mwmwmw. I would suggest hopping on gitter and chatting about your problem there. I don't really have enough information with the code samples to know what exactly is going on with your setup, as it would probably require the full source code. I find framebuffers tricky to get correct as when they fail it's hard to see why.

I'm not sure this issue is specifically actionable as the issue isn't reproducible, but is probably related to better docs or better debugging tools. If you have specific suggestions I can file new issues or find existing ones to track with.

**Comment by oveddan** [comment]
@mwmwmw  @gregtatum  I have the same problem.  I wish there were more examples/better documentation on how to use framebuffers, in particular how to render to an offscreen buffer and copy to a texture.

**Comment by edeetee** [comment]
For anyone in the future, I managed to fix this by setting depthStencil to false in the fbo constructor. Dunno why that works, just replicated what I saw in https://github.com/regl-project/regl/blob/gh-pages/example/life.js
