### ISSUE TITLE
Context lost when using regl.texture() inside a uniform with regl.frame()

### ISSUE THREAD

**Issue by terabaud** [regl-project/regl#508]
I tried to experiment with the regl.texture() api (following the texture example) and made a Codepen demo with a deformed placekitten image for this week's Codepen Error 500 challenge: 

https://codepen.io/terabaud/pen/NLyLLG

At some point, it crashes with the error message `context lost`. For a quicker crash, use a bigger kitten, like `kitty.src = 'https://placekitten.com/1000/1000'`

I guess there is some cleanup code missing at some point, like a `texture.destroy()`? Can you provide an example of the correct usage of `regl.texture()` here?

**Comment by terabaud** [comment]
Fixed the demo by moving the regl.texture() call out of the uniforms definition. The crash happens when you define the texture uniform like this:

```
texture: ctx => regl.texture(kitty),
```

**Comment by rreusser** [comment]
@terabaud I think it was perhaps crashing because the above code allocates a new texture on _every_ frame. Consider the difference between this:

```javascript
regl({
  ...
  uniforms: {
    texture: regl.texture(kitty)
  }
})
```

which only allocates a texture by calling `regl.texture` _once_ when the command is defined, and this:

```javascript
regl({
  ...
  uniforms: {
    texture: ctx => regl.texture(kitty)
  }
})
```

which runs the `regl.texture` code _every time_ the command is invoked. [This section in the docs](https://github.com/regl-project/regl/blob/master/API.md#inputs) has a bit more information about static vs. dynamic properties.

Glad it worked out, but please don't hesitate to follow up with any other questions you might run into!
