### ISSUE TITLE
Changes in rendering since v.1.3.11

### ISSUE THREAD

**Issue by archmoj** [regl-project/regl#565]
@rreusser thanks for the quick (.AND. great) follow ups of my PRs today regarding es5 issues in latest `regl` releases. 

Now that those issues fixed, I noticed rather remarkable changes to `plotly.js` baselines, when trying to upgrade from regl `v1.3.11` to `v1.5.2`.
You can compare the left and right images in this [demo](https://codepen.io/MojtabaSamimi/pen/oNjRmLa?editors=1000).

Any idea which of the PRs / direct commits to master caused this change of behaviour?

cc: @dy @mikolalysenko @alexcjohnson

**Comment by dy** [comment]
I'd speculate that's something related to blending mode.

**Comment by rreusser** [comment]
Seconded on blending mode. It feels like a premultiplied alpha thing (see: [Alpha Blending: To Pre or Not To Pre](https://developer.nvidia.com/content/alpha-blending-pre-or-not-pre)), but the one on the right looks unreasonably desaturated so I'm not sure that's quite it, though a more general blending mode issue seems possible.

There still seem like a fair number of possibilities for what could have caused it. To start, are you able to bisect and narrow it down to a specific version bump? [I see](https://www.npmjs.com/package/regl):

1.3.11
1.3.12
1.3.13
1.4.0
1.41
1.4.2
1.5.0
1.5.1
1.5.2

**Comment by rreusser** [comment]
Okay, I was pretty interested in getting to the bottom of this, so I did the above steps and found the faulty line:

https://github.com/regl-project/regl/commit/f6f02243dd26c472ec220034159d995408704ab7#diff-80ba86a622f2a9e5e014af98db071b0aR184

If I understand correctly, it looks like that flag exists to signal whether the canvas context is composited with the surrounding content with either the assumption that alpha is premultiplied or not: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext

More analysis to be done, but posting now in case you're also debugging.

**Comment by archmoj** [comment]
@rreusser @dy thanks for the analysis.
I think (& to keep patches backward compatible) that line should be 
```js
contextAttributes.premultipliedAlpha = contextAttributes.premultipliedAlpha || true
```
`premultipliedAlpha` in WebGL & `stackgl` is considered to be true by default.

**Comment by rreusser** [comment]
Oof, I'm a bit confused, but I did create this which lets you explore it:

https://codepen.io/rsreusser/pen/MWadREw?editors=1010

Basically just monkey-patches context creation to add this default or override the value. Okay, because I have to work through this carefully, here's what I see for the old (1.3.11) and new (1.5.2) behavior:

Unspecified (current status quo):
old: good
new: bad

Default false:
old: bad:
new: bad

Default true:
old: good
new: bad

Override false:
old: bad
new: bad

Override true:
old: good
new: good

**Comment by rreusser** [comment]
Okay, yeah, I'm inclined to agree. If regl specifies a default where there is none in order to patch over the fact that some browser supplies the wrong default, then it should mirror the browser default, which seems to be true.

@mikolalysenko @dy it does seem like this is subtly undesirable behavior since it disagrees with what appears to be browser defaults for `premultipliedAlpha`. It can be fixed at the user level by requesting users specify it manually, but the path of least resistance seems to be to remove regl's preference for a default which differs from browser defaults. That seems perhaps significant enough to warrant regl 2.0.0. 😮

**Comment by dy** [comment]
@rreusser the breaking behavior is added by minor v1.5.2, for "consistency" I'd opt for minor bump, although major is more correct.

**Comment by rreusser** [comment]
Oh, my mistake. I thought this was older! Yeah, it's pretty recent. How about just 1.6.0. 🤷 

Regarding preferred default, it [seems to be true](https://www.khronos.org/registry/webgl/specs/1.0/#WEBGLCONTEXTATTRIBUTES):

```
dictionary WebGLContextAttributes {
    ...
    GLboolean premultipliedAlpha = true;
};
```

**Comment by rreusser** [comment]
PR'd! https://github.com/regl-project/regl/pull/566
