### ISSUE TITLE
Empty scope command fails to render

### ISSUE THREAD

**Issue by kevzettler** [regl-project/regl#596]
I'm messing around with a generated tree-like structure of scoped commands. I found some unexpected behavior that seems to fail silently.  You can reproduce by modifying the bunny example https://github.com/regl-project/regl/blob/master/example/bunny.js

and change `drawBunny()` to `drawBunny({}, () => {})` it will not render the bunny and throws no errors or warnings. I would expect it to render the bunny.

**Comment by rreusser** [comment]
I think if you pass it a callback, it presumes you will instead be calling nested commands, so that to trigger a draw you must explicitly call `regl.draw()`. Which…… isn't documented… Hm. I learned about it here: https://github.com/regl-project/regl/blob/1f8fdad41409695c70902e770a768bf9c8a6a34f/example/life.js#L80
