### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by torchesburn** [regl-project/regl#667]
Not had a release since 2020.

Does seem like a very nice way to develop webgl applications as it nicely encapsulates the shader part of the code instead of abstracting it away in some nested function.

**Comment by rreusser** [comment]
There are certainly a couple incremental improvements or bugfixes around the edge which would be nice, but I think it's better to think of regl as (nearly) complete rather than abandoned. It aims to wrap the WebGL library completely and it does just that. I use it all the time and made this just a couple days ago: https://observablehq.com/d/9ac731e591350692 I believe it's in use in various commercial projects as well.

That said, regl doesn't (and won't) aim to address WebGL 2 which now has pretty good support, and emerging WebGPU is significantly more powerful. You might try checking out this project by @adnanwahab which is sort of regl meets webgpu: https://github.com/stackgpu/Simple-GPU

**Comment by torchesburn** [comment]
Very good point. That is how I will think of it. 

So WebGL2 for regl? that's a damn shame.
